name: Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  bump-patch:
    if: ${{ ($CI_COMMIT_MESSAGE =~ /^fix .*$/) && (github.ref == 'refs/heads/master') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump PATCH version
        run: |
          git config --global user.name "${ACTOR_NAME}"
          git config --global user.email "${ACTOR_EMAIL}"
          npm install
          npm run release:patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTOR_NAME: ${{ secrets.ACTOR_NAME }}
          ACTOR_EMAIL: ${{ secrets.ACTOR_EMAIL }}

  bump-minor:
    if: ${{ ($CI_COMMIT_MESSAGE =~ /^feature .*$/) && (github.ref == 'refs/heads/master') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump MINOR version
        run: |
          git config --global user.name "${ACTOR_NAME}"
          git config --global user.email "${ACTOR_EMAIL}"
          npm install
          npm run release:minor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTOR_NAME: ${{ secrets.ACTOR_NAME }}
          ACTOR_EMAIL: ${{ secrets.ACTOR_EMAIL }}

  deploy-preview:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [bump-patch, bump-minor]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run release script
        run: |
          git config --global user.name "${ACTOR_NAME}"
          git config --global user.email "${ACTOR_EMAIL}"
          npm install
          npm run release:minor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTOR_NAME: ${{ secrets.ACTOR_NAME }}
          ACTOR_EMAIL: ${{ secrets.ACTOR_EMAIL }}
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
